#ifndef BRONCHA_REACTNATIVEFLIPT_H
#define BRONCHA_REACTNATIVEFLIPT_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace broncha_reactnativeflipt {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* BRONCHA_REACTNATIVEFLIPT_H */