// Generated by uniffi-bindgen-react-native
#include "broncha-react-native-flipt.h"
#include "generated/flipt_react_native.hpp"

namespace broncha_reactnativeflipt {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeFliptReactNative::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}