// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-flipt.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "FliptSpec.h"

@interface Flipt : NSObject <NativeFliptSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Flipt : NSObject <RCTBridgeModule>
#endif

@end