// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "broncha-react-native-flipt.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "FliptSpec.h"

@interface ReactNativeFlipt : NSObject <NativeReactNativeFliptSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNativeFlipt : NSObject <RCTBridgeModule>
#endif

@end